language: php

branches:
  only:
    - master
    - develop

env:
  - MAGENTO_VERSION="magento-mirror-1.4.2.0" INSTALL_FOLDER="." DB=mysql
  - MAGENTO_VERSION="magento-mirror-1.5.1.0" INSTALL_FOLDER="./" DB=mysql
  - MAGENTO_VERSION="magento-ce-1.6.2.0" INSTALL_FOLDER="./magento" DB=mysql
  - MAGENTO_VERSION="magento-ce-1.7.0.2" INSTALL_FOLDER="magento-ce-1.7.0.2" DB=mysql
  - MAGENTO_VERSION="magento-ce-1.8.0.0" INSTALL_FOLDER="magento-ce-1.8.0.0" DB=mysql

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - export N98_MAGERUN_TEST_MAGENTO_ROOT="${INSTALL_FOLDER}"
  - mkdir subfolder && cd subfolder
  - ../bin/n98-magerun install --magentoVersionByName="${MAGENTO_VERSION}" --installationFolder="${INSTALL_FOLDER}" --dbHost=localhost --dbUser=root --dbPass='' --dbName="magento_travis" --installSampleData=yes --useDefaultConfigParams=yes --baseUrl="http://travis.magento.local/"

script:
  - vendor/bin/phpunit
  - php tests/check-coverage.php clover.xml 65