commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-1.6.2.0:
        version: 1.6.2.0
        dist:
          url: http://www.magentocommerce.com/downloads/assets/1.6.2.0/magento-1.6.2.0.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: magento-ce-1.7.0.2:
        version: 1.7.0.2
        dist:
          url: http://www.magentocommerce.com/downloads/assets/1.7.0.2/magento-1.7.0.2.tar.gz
          type: tar
        extra:
          sample-data: sample-data-1.6.1.0

      - name: mageplus-master
        version: dev-master
        source:
          url: https://github.com/mageplus/mageplus.git
          type: git
          reference: master
        extra:
          sample-data: sample-data-1.6.1.0

      - name: magelts-master
        version: dev-master
        source:
          url: https://github.com/mageLTS/mageLTS.git
          type: git
          reference: master
        extra:
          sample-data: sample-data-1.6.1.0

      - name: magelts-1.4.2.0
        version: 1.4.2.0
        source:
          url: https://github.com/mageLTS/mageLTS.git
          type: git
          reference: 1.4.2.0
        extra:
          sample-data: sample-data-1.1.2

      - name: magelts-1.5.1.0
        version: 1.5.1.0
        source:
          url: https://github.com/mageLTS/mageLTS.git
          type: git
          reference: 1.5.1.0
        extra:
          sample-data: sample-data-1.1.2

      - name: magelts-1.6.2.0
        version: 1.6.2.0
        source:
          url: https://github.com/mageLTS/mageLTS.git
          type: git
          reference: 1.6.2.0
        extra:
          sample-data: sample-data-1.6.1.0

    demo-data-packages:
      - name: sample-data-1.6.1.0
        version: 1.6.1.0
        dist:
          url: http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.tar.gz
          type: tar
      - name: sample-data-1.1.2
        version: 1.1.2
        dist:
          url: http://www.magentocommerce.com/downloads/assets/1.1.2/magento-sample-data-1.1.2.tar.bz2
          type: tar

    installation:
      defaults:
        currency: EUR
        locale: de_DE
        timezone: Europe/Berlin
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: admin
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com

  N98\Magento\Command\Database\DumpCommand:
    table-groups:
      - id: log
        description: Log tables
        tables: log_url log_url_info log_visitor log_visitor_info log_visitor_online report_event
      - id: dataflowtemp
        description: Temporary tables of the dataflow import/export tool
        tables: dataflow_batch_import dataflow_batch_export
      - id: stripped
        description: Standard definition for a stripped dump (logs and dataflow)
        tables: @stripped @log @dataflowtemp
      - id: sales
        description: Sales data (orders, invoices, creditmemos etc)
        tables: sales_order_* sales_flat_order_* sales_flat_creditmemo_* sales_flat_invoice_* sales_flat_quote sales_recurring_* sales_refunded_* sales_payment_*
      - id: customers
        description: Customer data
        tables: customer_address* customer_entity*
      - id: trade
        description: Current trade data (customers and orders). You usally do not want those in developer systems.
        tables: @customers @sales
      - id: development
        description: Removes logs and trade data so developers do not have to work with real customer data
        tables: @trade @stripped